services:
  bot:
    build: ..
    volumes:
      - ../db:/app/db:rw
      - ../config.json:/app/config.json:ro
    environment:
      - TOKEN=${TOKEN}
      - VSTUP_URL=${VSTUP_URL}
      - DEBUG=${DEBUG}